# =============================================================================
# MCP_PLATFORM install-hooks.ps1 — one-command hook installer (PowerShell)
# Installs all Git hooks from scripts/hooks/ into .git/hooks/
# On Windows, installs PowerShell-aware shims so Git calls the .ps1 hooks.
# Idempotent — safe to re-run.
# Usage: .\scripts\install-hooks.ps1 [-DryRun]
# =============================================================================
[CmdletBinding()]
param([switch]$DryRun)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Write-Fail { param([string]$m) Write-Host "[FAIL] $m" -ForegroundColor Red;    throw $m }
function Write-OK   { param([string]$m) Write-Host "[OK]   $m" -ForegroundColor Green }
function Write-Warn { param([string]$m) Write-Host "[WARN] $m" -ForegroundColor Yellow }
function Write-Dry  { param([string]$m) Write-Host "[DRY]  Would $m" -ForegroundColor Yellow }

Write-Host "--------------------------------------------"
Write-Host " MCP_PLATFORM hook installer (PowerShell)"
if ($DryRun) { Write-Host " (DRY RUN — no changes will be made)" }
Write-Host "--------------------------------------------"

$RepoRoot  = git rev-parse --show-toplevel
$HooksSrc  = Join-Path $RepoRoot "scripts\hooks"
$HooksDest = Join-Path $RepoRoot ".git\hooks"

if (-not (Test-Path $HooksSrc))  { Write-Fail "Hook sources not found at $HooksSrc" }
if (-not (Test-Path $HooksDest)) { Write-Fail ".git\hooks directory not found — is this a git repo?" }

$hooks = @('pre-commit', 'pre-push', 'commit-msg')

foreach ($hook in $hooks) {
    $ps1Src  = Join-Path $HooksSrc "${hook}.ps1"
    $bashSrc = Join-Path $HooksSrc $hook
    $dest    = Join-Path $HooksDest $hook

    # Decide what to install: prefer a PowerShell-aware shim
    $hasBash = Test-Path $bashSrc
    $hasPs1  = Test-Path $ps1Src

    if (-not $hasBash -and -not $hasPs1) {
        Write-Warn "No source found for $hook — skipping"
        continue
    }

    # Build the shim content
    # On Windows, Git calls hooks as shell scripts via sh.exe (from Git for Windows).
    # This shim detects pwsh availability and delegates; falls back to bash hook.
    $shimContent = @"
#!/usr/bin/env sh
# MCP_PLATFORM hook shim — auto-generated by install-hooks.ps1
# Delegates to PowerShell hook if pwsh is available, else runs bash hook.
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
HOOK_NAME="${hook}"
PS1_HOOK="\$(git rev-parse --show-toplevel)/scripts/hooks/\${HOOK_NAME}.ps1"
BASH_HOOK="\$(git rev-parse --show-toplevel)/scripts/hooks/\${HOOK_NAME}"

if command -v pwsh >/dev/null 2>&1; then
  exec pwsh -NoProfile -ExecutionPolicy Bypass -File "\$PS1_HOOK" "\$@"
elif command -v powershell >/dev/null 2>&1; then
  exec powershell -NoProfile -ExecutionPolicy Bypass -File "\$PS1_HOOK" "\$@"
elif [ -f "\$BASH_HOOK" ]; then
  exec sh "\$BASH_HOOK" "\$@"
else
  echo "[WARN] No executable hook found for \$HOOK_NAME"
  exit 0
fi
"@

    if ($DryRun) {
        Write-Dry "write shim for $hook → $dest"
        continue
    }

    # Backup existing hook if not ours
    if (Test-Path $dest) {
        $existing = Get-Content $dest -Raw -ErrorAction SilentlyContinue
        if ($existing -and $existing -notmatch 'MCP_PLATFORM') {
            Copy-Item $dest "${dest}.bak"
            Write-Warn "Backed up existing $hook to ${hook}.bak"
        }
    }

    Set-Content -Path $dest -Value $shimContent -Encoding UTF8 -NoNewline:$false
    # Mark executable (relevant for WSL and Git for Windows)
    if ($IsLinux -or $IsMacOS) {
        & chmod +x $dest
    }
    Write-OK "Installed shim: $hook"
}

# ── Validate ──────────────────────────────────────────────────────────────────
if (-not $DryRun) {
    Write-Host ""
    Write-Host "Installed hooks:"
    foreach ($hook in $hooks) {
        $dest = Join-Path $HooksDest $hook
        if (Test-Path $dest) {
            Write-OK "$hook — present ✓"
        } else {
            Write-Warn "$hook — NOT found"
        }
    }

    Write-Host ""
    Write-Host "Test with:"
    Write-Host "  git diff --cached | Select-Object -First 5"
    Write-Host "  .\scripts\check-guardrails.ps1 -Mode staged"
}

Write-Host "--------------------------------------------"
Write-Host "Hook installation complete." -ForegroundColor Green
exit 0
